import './globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import { Navbar } from '../components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'Pokemon App',
  description: 'Generated by create next app',
  authors: [{ name: 'Benjamin Miranda', url: '/' }],
  keywords: ['Pokemon', 'Pokedex'],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="purple-dark text-foreground bg-background h-screen">
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
